name: "Setup cargo"
description: Restore cargo cache and install dependencies

runs:
  using: "composite"
  steps:
    - name: Restore cargo cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Install dependencies
      run: |
        cargo update
      shell: bash
